var FRUITS_META = {
  LAST_UPDATED: "2026-06-09T12:00:00Z"
};

var FRUITS = [
  // ==================== COMMON (7) ====================
  { name: "Rocket",  rarity: "common",   value: 5000,      perm: 5000000,    demand: "low",    trend: "stable", glow: "#6b7196",  anim: "launch", img: "Rocket_Fruit.png",    beli: 5000,   robux: 50,   type: "Natural" },
  { name: "Spin",    rarity: "common",   value: 7500,      perm: 5000000,    demand: "low",    trend: "stable", glow: "#6b7196",  anim: "spin",   img: "Spin_Fruit.png",     beli: 7500,   robux: 75,   type: "Natural" },
  { name: "Blade",   rarity: "common",   value: 50000,     perm: 5000000,    demand: "low",    trend: "stable", glow: "#bdc3c7",  anim: "slash",  img: "Blade_Fruit.png",    beli: 30000,  robux: 100,  type: "Natural" },
  { name: "Spring",  rarity: "common",   value: 60000,     perm: 5000000,    demand: "low",    trend: "stable", glow: "#8b7a5e",  anim: "bounce", img: "Spring_Fruit.png",   beli: 60000,  robux: 180,  type: "Natural" },
  { name: "Bomb",    rarity: "common",   value: 80000,     perm: 5000000,    demand: "low",    trend: "stable", glow: "#6b7196",  anim: "float",  img: "Bomb_Fruit.png",     beli: 80000,  robux: 220,  type: "Natural" },
  // --- Bomb Skins ---
  { name: "Nuclear Bomb",       rarity: "limited", value: 290000000,   perm: 0, demand: "high",    trend: "up",    glow: "#2ecc71", anim: "float",  img: "Nuclear_Bomb_Fruit.png",    beli: 0,  robux: 0, type: "Limited" },
  { name: "Thermite Bomb",      rarity: "limited", value: 290000000,   perm: 0, demand: "high",    trend: "up",    glow: "#e67e22", anim: "float",  img: "Thermite_Bomb_Fruit.png",   beli: 0,  robux: 0, type: "Limited" },
  { name: "Azura Bomb",         rarity: "limited", value: 290000000,   perm: 0, demand: "high",    trend: "up",    glow: "#3498db", anim: "float",  img: "Azura_Bomb_Fruit.png",      beli: 0,  robux: 0, type: "Limited" },
  { name: "Celebration Bomb",   rarity: "limited", value: 5000000,     perm: 0, demand: "low",     trend: "stable", glow: "#f1c40f", anim: "float",  img: "Celebration_Bomb_Fruit.png", beli: 0,  robux: 0, type: "Limited" },
  { name: "Smoke",   rarity: "common",   value: 100000,    perm: 5000000,    demand: "low",    trend: "stable", glow: "#9ca3c4",  anim: "smoke",  img: "Smoke_Fruit.png",    beli: 100000, robux: 250,  type: "Elemental" },
  { name: "Spike",   rarity: "common",   value: 180000,    perm: 5000000,    demand: "low",    trend: "stable", glow: "#6b7196",  anim: "pulse",  img: "Spike_Fruit.png",    beli: 180000, robux: 380,  type: "Natural" },

  // ==================== UNCOMMON (6) ====================
  { name: "Flame",   rarity: "uncommon", value: 250000,    perm: 12000000,   demand: "low",    trend: "stable", glow: "#e67e22",  anim: "fire",   img: "Flame_Fruit.png",    beli: 250000, robux: 550,  type: "Elemental" },
  { name: "Ice",     rarity: "uncommon", value: 550000,    perm: 12000000,   demand: "low",    trend: "stable", glow: "#3498db",  anim: "frost",  img: "Ice_Fruit.png",      beli: 350000, robux: 750,  type: "Elemental" },
  { name: "Sand",    rarity: "uncommon", value: 420000,    perm: 12000000,   demand: "low",    trend: "stable", glow: "#c2a64e",  anim: "shake",  img: "Sand_Fruit.png",     beli: 420000, robux: 850,  type: "Elemental" },
  { name: "Dark",    rarity: "uncommon", value: 400000,    perm: 12000000,   demand: "low",    trend: "stable", glow: "#2c3e50",  anim: "void",   img: "Dark_Fruit.png",     beli: 500000, robux: 950,  type: "Elemental" },
  { name: "Eagle",   rarity: "uncommon", value: 500000,    perm: 12000000,   demand: "low",    trend: "stable", glow: "#8b7a5e",  anim: "float",  img: "Eagle_Fruit.png",    beli: 550000, robux: 975,  type: "Beast" },
  // --- Eagle Skins ---
  { name: "Glacier Eagle",      rarity: "limited", value: 10000000,    perm: 0, demand: "low",     trend: "stable", glow: "#74b9ff", anim: "float",  img: "Glacier_Eagle_Fruit.png",  beli: 0,  robux: 0, type: "Limited" },
  { name: "Requiem Eagle",      rarity: "limited", value: 110000000,   perm: 0, demand: "medium",  trend: "stable", glow: "#6c5ce7", anim: "float",  img: "Requiem_Eagle_Fruit.png",  beli: 0,  robux: 0, type: "Limited" },
  { name: "Matrix Eagle",       rarity: "limited", value: 170000000,   perm: 0, demand: "medium",  trend: "up",    glow: "#00b894", anim: "float",  img: "Matrix_Eagle_Fruit.png",   beli: 0,  robux: 0, type: "Limited" },
  { name: "Parrot Eagle",       rarity: "limited", value: 80000000,    perm: 0, demand: "low",     trend: "stable", glow: "#e84393", anim: "float",  img: "Parrot_Eagle.png",         beli: 0,  robux: 0, type: "Limited" },
  { name: "Diamond", rarity: "uncommon", value: 500000,    perm: 12000000,   demand: "low",    trend: "stable", glow: "#a29bfe",  anim: "glow",   img: "Diamond_Fruit.png",  beli: 600000, robux: 1000, type: "Natural" },
  // --- Diamond Skins ---
  { name: "Emerald Diamond",    rarity: "limited", value: 80000000,    perm: 0, demand: "medium", trend: "stable", glow: "#2ecc71", anim: "glow",  img: "Emerald_Diamond_Fruit.png",     beli: 0,  robux: 0, type: "Limited" },
  { name: "Rose Quartz Diamond",rarity: "limited", value: 110000000,   perm: 0, demand: "medium", trend: "stable", glow: "#e84393", anim: "glow",  img: "Rose_Quartz_Diamond_Fruit.png",  beli: 0,  robux: 0, type: "Limited" },
  { name: "Topaz Diamond",      rarity: "limited", value: 80000000,    perm: 0, demand: "medium", trend: "stable", glow: "#f1c40f", anim: "glow",  img: "Topaz_Diamond_Fruit.png",       beli: 0,  robux: 0, type: "Limited" },
  { name: "Ruby Diamond",        rarity: "limited", value: 60000000,    perm: 0, demand: "low",    trend: "stable", glow: "#e74c3c", anim: "glow",  img: "Ruby_Diamond_Fruit.png",        beli: 0,  robux: 0, type: "Limited" },

  // ==================== RARE (4) ====================
  { name: "Light",   rarity: "rare",     value: 1200000,   perm: 30000000,   demand: "low",    trend: "stable", glow: "#f1c40f",  anim: "glow",   img: "Light_Fruit.png",    beli: 650000, robux: 1100, type: "Elemental" },
  { name: "Rubber",  rarity: "rare",     value: 1400000,   perm: 35000000,   demand: "low",    trend: "stable", glow: "#e74c3c",  anim: "bounce", img: "Rubber_Fruit.png",   beli: 750000, robux: 1200, type: "Natural" },
  { name: "Ghost",   rarity: "rare",     value: 950000,    perm: 22000000,   demand: "low",    trend: "stable", glow: "#95a5a6",  anim: "fade",   img: "Ghost_Fruit.png",    beli: 940000, robux: 1275, type: "Natural" },
  { name: "Magma",   rarity: "rare",     value: 1300000,   perm: 32000000,   demand: "medium", trend: "stable", glow: "#e74c3c",  anim: "fire",   img: "Magma_Fruit.png",    beli: 960000, robux: 1300, type: "Elemental" },

  // ==================== LEGENDARY (11) ====================
  { name: "Quake",    rarity: "legendary", value: 2000000,  perm: 55000000,   demand: "medium", trend: "stable", glow: "#9b59b6", anim: "quake",  img: "Quake_Fruit.png",    beli: 1000000, robux: 1500, type: "Natural" },
  { name: "Buddha",   rarity: "legendary", value: 15000000, perm: 350000000,  demand: "high",   trend: "down",   glow: "#f39c12", anim: "glow",   img: "Buddha_Fruit.png",   beli: 1200000, robux: 1650, type: "Beast" },
  { name: "Love",     rarity: "legendary", value: 2700000,  perm: 75000000,   demand: "medium", trend: "stable", glow: "#e84393", anim: "heart",  img: "Love_Fruit.png",     beli: 1300000, robux: 1700, type: "Natural" },
  { name: "Creation", rarity: "legendary", value: 2500000,  perm: 70000000,   demand: "medium", trend: "stable", glow: "#00cec9", anim: "glow",   img: "Creation_Fruit.png", beli: 1400000, robux: 1750, type: "Natural" },
  { name: "Spider",   rarity: "legendary", value: 3300000,  perm: 95000000,   demand: "medium", trend: "stable", glow: "#8e44ad", anim: "web",    img: "Spider_Fruit.png",   beli: 1500000, robux: 1800, type: "Natural" },
  { name: "Sound",    rarity: "legendary", value: 2500000,  perm: 300000000,  demand: "medium", trend: "stable", glow: "#00cec9", anim: "wave",   img: "Sound_Fruit.png",    beli: 1700000, robux: 1900, type: "Natural" },
  { name: "Phoenix",  rarity: "legendary", value: 2800000,  perm: 350000000,  demand: "medium", trend: "stable", glow: "#e17055", anim: "fire",   img: "Phoenix_Fruit.png",  beli: 1800000, robux: 2000, type: "Beast" },
  { name: "Portal",   rarity: "legendary", value: 10000000,  perm: 220000000,  demand: "high",   trend: "up",     glow: "#00b894", anim: "portal", img: "Portal_Fruit.png",   beli: 1900000, robux: 2000, type: "Natural" },
  // --- Portal Skins ---
  { name: "Divine Portal",      rarity: "limited", value: 430000000,   perm: 0, demand: "extreme", trend: "up",    glow: "#f1c40f", anim: "portal", img: "Divine_Portal_Fruit.png", beli: 0,  robux: 0, type: "Limited" },
  { name: "Lightning",rarity: "legendary", value: 60000000,  perm: 485000000,  demand: "high", trend: "stable", glow: "#fdcb6e", anim: "lightning", img: "Lightning_Fruit.png", beli: 2100000, robux: 2100, type: "Elemental" },
  // --- Lightning Skins ---
  { name: "Purple Lightning",   rarity: "limited", value: 2690000000,  perm: 0, demand: "extreme", trend: "up",    glow: "#9b59b6", anim: "lightning", img: "Purple_Lightning_Fruit.png",  beli: 0,  robux: 0, type: "Limited" },
  { name: "Yellow Lightning",   rarity: "limited", value: 800000000,   perm: 0, demand: "high",    trend: "up",    glow: "#f1c40f", anim: "lightning", img: "Yellow_Lightning_Fruit.png",  beli: 0,  robux: 0, type: "Limited" },
  { name: "Green Lightning",    rarity: "limited", value: 150000000,   perm: 0, demand: "medium",  trend: "stable", glow: "#2ecc71", anim: "lightning", img: "Green_Lightning_Fruit.png",   beli: 0,  robux: 0, type: "Limited" },
  { name: "Red Lightning",      rarity: "limited", value: 710000000,   perm: 0, demand: "high",    trend: "up",    glow: "#e74c3c", anim: "lightning", img: "Red_Lightning_Fruit.png",     beli: 0,  robux: 0, type: "Limited" },
  // --- Pain Skins ---
  { name: "Sadness Pain",       rarity: "limited", value: 290000000,   perm: 0, demand: "high",    trend: "up",    glow: "#3498db", anim: "shake",  img: "Sadness_Fruit.png",          beli: 0,  robux: 0, type: "Limited" },
  { name: "Torment Pain",       rarity: "limited", value: 50000000,    perm: 0, demand: "low",     trend: "stable", glow: "#2c3e50", anim: "shake",  img: "Torment_Fruit.png",          beli: 0,  robux: 0, type: "Limited" },
  { name: "Frustration Pain",   rarity: "limited", value: 240000000,   perm: 0, demand: "medium",  trend: "stable", glow: "#e74c3c", anim: "shake",  img: "Frustration_Fruit.png",      beli: 0,  robux: 0, type: "Limited" },
  { name: "Celestial Pain",     rarity: "limited", value: 270000000,   perm: 0, demand: "high",    trend: "up",    glow: "#f1c40f", anim: "shake",  img: "Celestial_Fruit.png",        beli: 0,  robux: 0, type: "Limited" },
  { name: "Super Spirit Pain",  rarity: "limited", value: 710000000,   perm: 0, demand: "extreme", trend: "up",    glow: "#9b59b6", anim: "shake",  img: "Super_Spirit_Pain_Fruit.png", beli: 0,  robux: 0, type: "Limited" },
  { name: "Blizzard", rarity: "legendary", value: 5000000,  perm: 500000000,  demand: "medium", trend: "stable", glow: "#74b9ff", anim: "frost",  img: "Blizzard_Fruit.png", beli: 2400000, robux: 2250, type: "Elemental" },

  // ==================== MYTHICAL (17) ====================
  { name: "Dragon (West)",  rarity: "mythical", value: 1450000000, perm: 2900000000, demand: "extreme", trend: "up",     glow: "#e74c3c", anim: "dragon",  img: "Dragon_(West)_Fruit.png",  beli: 15000000, robux: 5000, type: "Beast" },
  { name: "Dragon (East)",  rarity: "mythical", value: 1160000000, perm: 2900000000, demand: "extreme", trend: "up",     glow: "#2ecc71", anim: "dragon",  img: "Dragon_(East)_Fruit.png",  beli: 15000000, robux: 5000, type: "Beast" },
  // --- Dragon Skins ---
  { name: "Ember Dragon",       rarity: "limited", value: 3970000000,  perm: 0, demand: "extreme", trend: "up",    glow: "#e67e22", anim: "dragon", img: "Ember_Dragon_Fruit_(West).png",  beli: 0,  robux: 0, type: "Limited" },
  { name: "Eclipse Dragon",     rarity: "limited", value: 9000000000,  perm: 0, demand: "extreme", trend: "up",    glow: "#6c5ce7", anim: "dragon", img: "Dragon_(West)_Eclipse.png",      beli: 0,  robux: 0, type: "Limited" },
  { name: "Blood Moon Dragon",  rarity: "limited", value: 4000000000,  perm: 0, demand: "extreme", trend: "up",    glow: "#e74c3c", anim: "dragon", img: "Dragon_(West)_Blood_Moon.png",   beli: 0,  robux: 0, type: "Limited" },
  { name: "Phoenix Sky Dragon", rarity: "limited", value: 3500000000,  perm: 0, demand: "extreme", trend: "stable", glow: "#e17055", anim: "dragon", img: "Dragon_(West)_Phoenix_Sky.png",  beli: 0,  robux: 0, type: "Limited" },
  { name: "Violet Night Dragon",rarity: "limited", value: 3000000000,  perm: 0, demand: "extreme", trend: "stable", glow: "#8e44ad", anim: "dragon", img: "Dragon_(West)_Violet_Night.png", beli: 0,  robux: 0, type: "Limited" },
  { name: "Kitsune",    rarity: "mythical", value: 290000000,  perm: 2320000000, demand: "extreme", trend: "stable", glow: "#6c5ce7", anim: "kitsune", img: "Kitsune_Fruit.png",    beli: 8000000,  robux: 4000, type: "Beast" },
  { name: "Empyrean",   rarity: "mythical", value: 2960000000, perm: 5000000000, demand: "extreme", trend: "up",    glow: "#fd79a8", anim: "kitsune", img: "Empyrean_Fruit.png",   beli: 0,         robux: 0,    type: "Beast" },
  // --- Empyrean Skin ---
  { name: "Galaxy Empyrean",    rarity: "limited", value: 5350000000,  perm: 0, demand: "extreme", trend: "up",    glow: "#6c5ce7", anim: "kitsune", img: "Empyrean_Fruit_(Galaxy).png",  beli: 0,  robux: 0, type: "Limited" },
  { name: "Yeti",       rarity: "mythical", value: 160000000,  perm: 1740000000, demand: "high",    trend: "stable", glow: "#74b9ff", anim: "frost",   img: "Yeti_Fruit.png",      beli: 5000000,  robux: 3000, type: "Beast" },
  { name: "Fiend",      rarity: "mythical", value: 495000000,  perm: 1000000000, demand: "high",    trend: "stable", glow: "#6c5ce7", anim: "void",    img: "Fiend_Fruit.png",     beli: 0,         robux: 0,    type: "Beast" },
  { name: "Control", rarity: "mythical", value: 140000000,  perm: 1400000000, demand: "high",    trend: "stable", glow: "#00cec9", anim: "portal",  img: "Control_Fruit.png", beli: 9000000,  robux: 4000, type: "Natural" },
  { name: "Gas",     rarity: "mythical", value: 75000000,   perm: 1610000000, demand: "high",    trend: "up",     glow: "#00b894", anim: "toxic",   img: "Gas_Fruit.png",     beli: 3200000,  robux: 2500, type: "Elemental" },
  { name: "Tiger",    rarity: "mythical", value: 60000000,   perm: 1750000000, demand: "high",    trend: "stable", glow: "#e17055", anim: "pounce",  img: "Tiger_Fruit.png",    beli: 5000000,  robux: 3000, type: "Beast" },
  { name: "Werewolf", rarity: "mythical", value: 800000000,  perm: 1600000000, demand: "high",    trend: "stable", glow: "#2d3436", anim: "shake",   img: "Werewolf_Fruit.png", beli: 0,         robux: 0,    type: "Beast" },
  { name: "Dough",   rarity: "mythical", value: 30000000,   perm: 1450000000, demand: "high",    trend: "stable", glow: "#fdcb6e", anim: "bounce",  img: "Dough_Fruit.png",   beli: 2800000,  robux: 2400, type: "Elemental" },
  { name: "T-Rex",   rarity: "mythical", value: 20000000,   perm: 320000000,  demand: "high",    trend: "stable", glow: "#d63031", anim: "stomp",   img: "T-Rex_Fruit.png",   beli: 2700000,  robux: 2350, type: "Beast" },
  { name: "Mammoth", rarity: "mythical", value: 10000000,   perm: 1450000000, demand: "medium",  trend: "down",   glow: "#b2bec3", anim: "stomp",   img: "Mammoth_Fruit.png", beli: 2700000,  robux: 2350, type: "Beast" },
  { name: "Spirit",  rarity: "mythical", value: 10000000,   perm: 1000000000, demand: "medium",  trend: "stable", glow: "#9b59b6", anim: "spirit",  img: "Spirit_Fruit.png",  beli: 3400000,  robux: 2550, type: "Natural" },
  { name: "Venom",   rarity: "mythical", value: 10000000,   perm: 1000000000, demand: "medium",  trend: "stable", glow: "#6c5ce7", anim: "toxic",   img: "Venom_Fruit.png",   beli: 3000000,  robux: 2450, type: "Natural" },
  { name: "Shadow",  rarity: "mythical", value: 10000000,    perm: 180000000,  demand: "medium",  trend: "stable", glow: "#2d3436", anim: "void",    img: "Shadow_Fruit.png",  beli: 2900000,  robux: 2425, type: "Natural" },
  { name: "Gravity", rarity: "mythical", value: 5500000,    perm: 170000000,  demand: "medium",  trend: "down",   glow: "#636e72", anim: "float",   img: "Gravity_Fruit.png", beli: 2500000,  robux: 2300, type: "Natural" },

  // ==================== GAMEPASSES / SCROLLS ====================
  { name: "Fruit Notifier",    rarity: "gamepass", value: 1650000000, perm: 0, demand: "extreme", trend: "stable", glow: "#f1c40f", anim: "glow",  img: "BadgeFruitNotifier.png", beli: 0,  robux: 2700, type: "Gamepass" },
  { name: "Dark Blade",        rarity: "gamepass", value: 580000000,  perm: 0, demand: "high",    trend: "stable", glow: "#2d3436", anim: "slash", img: "Dark_Blade.png",         beli: 0,  robux: 1200, type: "Gamepass" },
  { name: "Mythical Scrolls",  rarity: "gamepass", value: 400000000,  perm: 0, demand: "medium",  trend: "stable", glow: "#9b59b6", anim: "glow",  img: "Mythical_Scroll.png",   beli: 0,  robux: 1500, type: "Gamepass" },
  { name: "Legendary Scrolls", rarity: "gamepass", value: 230000000,  perm: 0, demand: "low",     trend: "stable", glow: "#3498db", anim: "glow",  img: "Legendary_Scroll.png",  beli: 0,  robux: 800,  type: "Gamepass" },
  { name: "+1 Fruit Storage",  rarity: "gamepass", value: 220000000,  perm: 0, demand: "high",    trend: "stable", glow: "#00b894", anim: "glow",  img: "BadgeFruitStorage.png",  beli: 0,  robux: 400,  type: "Gamepass" },
  { name: "2x Mastery",       rarity: "gamepass", value: 240000000,  perm: 0, demand: "high",    trend: "stable", glow: "#e17055", anim: "pulse", img: "BadgeMasteryx2.png",     beli: 0,  robux: 450,  type: "Gamepass" },
  { name: "2x Money",         rarity: "gamepass", value: 240000000,  perm: 0, demand: "high",    trend: "stable", glow: "#f1c40f", anim: "pulse", img: "BadgeMoneyx2.png",       beli: 0,  robux: 450,  type: "Gamepass" },
  { name: "2x Boss Drops",    rarity: "gamepass", value: 140000000,  perm: 0, demand: "medium",  trend: "stable", glow: "#e74c3c", anim: "pulse", img: "BadgeBossDrops.png",     beli: 0,  robux: 350,  type: "Gamepass" },
  { name: "Fast Boats",       rarity: "gamepass", value: 140000000,  perm: 0, demand: "medium",  trend: "stable", glow: "#3498db", anim: "float", img: "BadgeBoats.png",         beli: 0,  robux: 350,  type: "Gamepass" }
];

var FRUITS_DETAIL = {
  "Rocket":     { desc: "A basic rocket-propelled fruit. Great for beginners.", moves: ["Rocket Propulsion", "Blast Off", "Rocket Punch", "Missile Barrage", "Rocket Jump"], awakening: false, dropChance: "Spawns every 60 min. Common drop." },
  "Spin":       { desc: "Rapid spinning attacks with decent mobility.", moves: ["Spin Dash", "Cyclone Kick", "Whirlwind", "Tornado Spin", "Spin Launch"], awakening: false, dropChance: "Spawns every 60 min. Common drop." },
  "Blade":      { desc: "Throw sharp blade projectiles at your foes.", moves: ["Blade Toss", "Piercing Slash", "Blade Storm", "Blade Barrage", "Blade Dash"], awakening: false, dropChance: "Spawns every 60 min. Common drop." },
  "Spring":     { desc: "Bouncy springs for unique mobility and impacts.", moves: ["Spring Punch", "Spring Snipe", "Spring Cannon", "Spring Emperor", "Spring Leap"], awakening: false, dropChance: "Spawns every 60 min. Common drop." },
  "Bomb":       { desc: "Explosive bombs that deal heavy AOE damage.", moves: ["Targeted Bomb", "Bomb Grab", "Land Mines", "Self Destruct", "Explosive Jump"], awakening: false, dropChance: "Spawns every 60 min. Common drop." },
  "Smoke":      { desc: "Smoke-based attacks for evasion and area control.", moves: ["Smoke Slam", "Smoke Blast", "Smoke Screen", "Smoke Liberation", "Smoke Bomber"], awakening: false, dropChance: "Spawns every 60 min. Common drop." },
  "Spike":      { desc: "Generate spikes from the ground to attack.", moves: ["Spike Summon", "Whirlwind", "Spiky Ball", "Spike Trap", "Spike Barrage"], awakening: false, dropChance: "Spawns every 60 min. Common drop." },
  "Flame":      { desc: "Control fire with blazing AOE attacks.", moves: ["Fire Bullets", "Burning Blast", "Fire Column", "Flame Destroyer", "Fire Flight"], awakening: true, dropChance: "Spawns every 60 min. Uncommon spawn." },
  "Ice":        { desc: "Freeze enemies and create ice barriers.", moves: ["Ice Spears", "Ice Surge", "Ice Bird", "Glacial Epoch", "Ice Walk"], awakening: true, dropChance: "Spawns every 60 min. Uncommon spawn." },
  "Sand":       { desc: "Manipulate sand for desert-style combat.", moves: ["Desert Sword", "Desert Funeral", "Sand Tornado", "Heavy Sand", "Sand Flight"], awakening: true, dropChance: "Spawns every 60 min. Uncommon spawn." },
  "Dark":       { desc: "Darkness-based attacks with life drain.", moves: ["Dark Rocks", "Black Spiral", "Black Hole", "Dark Bomb", "Dark Flight"], awakening: true, dropChance: "Spawns every 60 min. Uncommon spawn." },
  "Eagle":      { desc: "Take flight as a mighty eagle with aerial strikes.", moves: ["Wind Burst", "Feather Storm", "Bone Crusher", "Soaring Talon", "Flight"], awakening: false, dropChance: "Dropped by Tyrant of the Skies." },
  "Diamond":    { desc: "Diamond-hard defense with reflective attacks.", moves: ["Encrust", "Shard Storm", "Shimmering Disruption", "Prismatic Reflection", "Diamond Body"], awakening: false, dropChance: "Spawns every 60 min. Uncommon spawn." },
  "Light":      { desc: "Fastest mobility fruit with light teleportation.", moves: ["Light Ray", "Barrage of Light", "Reflection Kick", "Sky Beam Barrage", "Light Flight"], awakening: true, dropChance: "Spawns every 60 min. Rare spawn." },
  "Rubber":     { desc: "Stretching combat inspired by elasticity.", moves: ["Cannon", "Smash", "Rush", "Transformation", "Slingshot"], awakening: false, dropChance: "Spawns every 60 min. Rare spawn." },
  "Ghost":      { desc: "Phase through attacks and possess enemies.", moves: ["Shivering Possession", "Spectral Release", "Cries of the Underworld", "Ghost Busters", "Wandering Soul"], awakening: false, dropChance: "Spawns every 60 min. Rare spawn." },
  "Magma":      { desc: "Lava damage and massive AOE eruptions.", moves: ["Magma Clap", "Magma Eruption", "Magma Fist", "Magma Meteors", "Magma Floor"], awakening: true, dropChance: "Spawns every 60 min. Rare spawn." },
  "Quake":      { desc: "Cause devastating earthquakes and tsunamis.", moves: ["Quake Punch", "Quake Wave", "Quake Erupt", "Dual Tsunami", "Quake Jump"], awakening: false, dropChance: "Spawns every 60 min. Legendary spawn." },
  "Buddha":     { desc: "Transform into Buddha for massive HP and damage.", moves: ["Transform", "Impact", "Buddha Leap", "Buddha Explosion", "Buddha Flight"], awakening: false, dropChance: "Spawns every 60 min. Legendary spawn." },
  "Love":       { desc: "Heart-based attacks with charming effects.", moves: ["Heart Shot", "Cupid's Zone", "Irresistible Attraction", "Besto Friendo", "Flamingo Ride"], awakening: false, dropChance: "Spawns every 60 min. Legendary spawn." },
  "Creation":   { desc: "Create objects and magical constructs.", moves: ["Batter Up", "Sleight of Hand", "Sword Box", "Magic City", "Fortify"], awakening: false, dropChance: "Spawns every 60 min. Legendary spawn." },
  "Spider":     { desc: "String-based attacks with web trapping.", moves: ["Spider Wraith", "Multi-string Attack", "Over-heated Sniper", "Ultimate Thread", "Spider Path"], awakening: false, dropChance: "Spawns every 60 min. Legendary spawn." },
  "Sound":      { desc: "Musical attacks with harmonic power.", moves: ["Rhapsody Notes", "Fortissimo", "Symphonic Radiance", "Glorious Harmony", "Tempo: Prestissimo"], awakening: false, dropChance: "Spawns every 60 min. Legendary spawn." },
  "Phoenix":    { desc: "Flame-based regeneration and flight.", moves: ["Cannon", "Regeneration Flames", "Fast Kick", "Full Transformation", "Hybrid Flight"], awakening: false, dropChance: "Spawns every 60 min. Legendary spawn." },
  "Portal":     { desc: "Teleport through dimensions and warp space.", moves: ["Portal Dash", "Parallel Escape", "World Warp", "Dimensional Rift", "Quantum Leap"], awakening: false, dropChance: "Spawns every 60 min. Legendary spawn." },
  "Lightning":  { desc: "Electric shocks and thunderstorm attacks.", moves: ["Lightning Orb", "Thunderstorm", "Sky Judgement", "Thunderball Destruction", "Electric Flash"], awakening: false, dropChance: "Spawns every 60 min. Legendary spawn." },
  "Pain":       { desc: "Suffer and deal pain with rage-fueled attacks.", moves: ["Fury Jab", "Rage Release", "Agony Nuke", "Torturing Pulse", "Torment Warp"], awakening: false, dropChance: "Spawns every 60 min. Legendary spawn." },
  "Blizzard":   { desc: "Control ice storms and freezing winds.", moves: ["Snowflake Shuriken", "White Out", "Howling Wind", "Blizzard Domain", "Tornado Flight"], awakening: false, dropChance: "Spawns every 60 min. Legendary spawn." },
  "Dragon (West)": { desc: "Transform into a mighty Western Dragon with scorching flames.", moves: ["Blazing Claws", "Heatwave Cannon", "Infernal Pincer", "Scorching Downfall", "Imperial Evolution", "Draconic Soar"], awakening: false, dropChance: "Obtained from Dragon Egg. Mythical spawn." },
  "Dragon (East)": { desc: "Transform into an Eastern Dragon with flowing fire attacks.", moves: ["Blazing Claws", "Heatwave Cannon", "Infernal Pincer", "Scorching Downfall", "Imperial Evolution", "Draconic Soar"], awakening: false, dropChance: "Obtained from Dragon Egg. Mythical spawn." },
  "Kitsune":    { desc: "Fox-like abilities with blue fire and transformation.", moves: ["Azure Slash", "Accursed Enchantment", "Tails of Burning Agony", "Fox Fire Disruption", "Transformation", "Wild Assault"], awakening: false, dropChance: "0.1% from Azure Ember offering at Kitsune Shrine." },
  "Empyrean":   { desc: "An ascended Kitsune mutation with empyrean blue flames and divine fox powers.", moves: ["Celestial Slash", "Divine Enchantment", "Infernal Tails", "Empyrean Firestorm", "Transformation", "Heavenly Assault"], awakening: false, dropChance: "Event-limited mutation. Acquired via Kitsune during special events." },
  "Yeti":       { desc: "Frost giant powers with ice-based destruction.", moves: ["Arctic Clap", "Frostbite Boulder", "Glacial Execution", "Transformation", "Tundra Rush"], awakening: false, dropChance: "Spawns rarely. Mythical spawn." },
  "Fiend":      { desc: "A corrupted Yeti mutation with demonic ice and hellish frost powers.", moves: ["Demonic Clap", "Hellfrost Boulder", "Abyssal Execution", "Transformation", "Fiendish Rush"], awakening: false, dropChance: "Event-limited mutation. Acquired via Yeti during special events." },
  "Control":    { desc: "Manipulate space and control domains.", moves: ["Domain Control", "Slice N' Dice", "Gamma Blade", "Teleport", "Transmutation"], awakening: false, dropChance: "Spawns very rarely. Mythical spawn (2nd rarest)." },
  "Gas":        { desc: "Toxic gas clouds and suffocating fumes.", moves: ["Suffocating Fumes", "Bursting Vapor", "Smog Demons", "Vapor Condensation", "Traveling Gas"], awakening: false, dropChance: "Spawns rarely. Mythical spawn." },
  "Tiger":      { desc: "A reworked beast fruit granting ferocious tiger claws with blazing form and enhanced speed.", moves: ["Finger Revolver", "Spiraling Kick", "Afterimage Assault", "Transformation", "Body Flicker"], awakening: false, dropChance: "Spawns rarely. Mythical spawn." },
  "Werewolf":   { desc: "A lunar Tiger mutation with savage wolf-like attacks under the full moon.", moves: ["Lunar Claw", "Howling Strike", "Moonlit Frenzy", "Transformation", "Pack Assault"], awakening: false, dropChance: "Event-limited mutation. Acquired via Tiger during special events." },
  "Dough":      { desc: "Control dough with stretchy, fiery attacks.", moves: ["Missile Jab", "Pastry River", "Piercing Clothesline", "Dough Fist Fusillade", "Scorching Donut"], awakening: false, dropChance: "Spawns rarely. Mythical spawn." },
  "T-Rex":      { desc: "Become a mighty T-Rex with devastating power.", moves: ["Tail Swipe", "Predatory Screech", "Hunter's Rage", "Reptilian Scales", "Gigantic Leap"], awakening: false, dropChance: "Spawns rarely. Mythical spawn." },
  "Mammoth":    { desc: "Ancient mammoth with earth-shaking stomps.", moves: ["Ancient Cutter", "True Prehistoric Punt", "Colossal Crusher", "Transformation", "Stampede"], awakening: false, dropChance: "Spawns rarely. Mythical spawn." },
  "Spirit":     { desc: "Summon spirits and control spectral energy.", moves: ["Frostfire Grasp", "Wrath of Ra", "Wrath of Shu", "End of Times", "Sky Ruler"], awakening: false, dropChance: "Spawns rarely. Mythical spawn." },
  "Venom":      { desc: "Poison daggers and toxic venom attacks.", moves: ["Poison Daggers", "Noxious Shot", "Toxic Fog", "Transformation", "Serpent's Wrath"], awakening: false, dropChance: "Spawns rarely. Mythical spawn." },
  "Shadow":     { desc: "Darkness manipulation with shadow summons.", moves: ["Somber Rebellion", "Shade Nest", "Nightmare Leech", "Corvus Torment", "Umbrage"], awakening: false, dropChance: "Spawns rarely. Mythical spawn." },
  "Gravity":    { desc: "Control gravity with crushing force.", moves: ["Singularity", "Orbital Chain", "Gravitational Prison", "Asteroid Crash", "Shooting Star"], awakening: false, dropChance: "Spawns rarely. Mythical spawn." },
  // --- Diamond Skins ---
  "Emerald Diamond":    { desc: "A CHROMATIC Diamond skin with an emerald green color scheme. Limited skin obtainable from Summer Gacha.", moves: ["Encrust", "Shard Storm", "Shimmering Disruption", "Prismatic Reflection", "Diamond Body"], awakening: false, dropChance: "Limited skin. Was obtainable from Summer Gacha (500 tokens)." },
  "Rose Quartz Diamond":{ desc: "A CHROMATIC Diamond skin with a pink rose quartz color scheme. Limited skin obtainable from Summer Gacha.", moves: ["Encrust", "Shard Storm", "Shimmering Disruption", "Prismatic Reflection", "Diamond Body"], awakening: false, dropChance: "Limited skin. Was obtainable from Summer Gacha (500 tokens)." },
  "Topaz Diamond":      { desc: "A CHROMATIC Diamond skin with a golden topaz color scheme. Limited skin obtainable from Summer Gacha.", moves: ["Encrust", "Shard Storm", "Shimmering Disruption", "Prismatic Reflection", "Diamond Body"], awakening: false, dropChance: "Limited skin. Was obtainable from Summer Gacha (500 tokens)." },
  "Ruby Diamond":       { desc: "A CHROMATIC Diamond skin with a deep ruby red color scheme. Limited skin obtainable from Red Gacha.", moves: ["Encrust", "Shard Storm", "Shimmering Disruption", "Prismatic Reflection", "Diamond Body"], awakening: false, dropChance: "Limited skin. Was obtainable from Red Gacha (250 tokens)." },
  // --- Lightning Skins ---
  "Purple Lightning":   { desc: "A CHROMATIC Lightning skin with a purple color scheme. Extremely rare limited skin from Summer Gacha.", moves: ["Lightning Orb", "Thunderstorm", "Sky Judgement", "Thunderball Destruction", "Electric Flash"], awakening: false, dropChance: "Limited skin. Was obtainable from Summer Gacha (500 tokens)." },
  "Yellow Lightning":   { desc: "A CHROMATIC Lightning skin with a yellow color scheme. Rare limited skin from Summer Gacha.", moves: ["Lightning Orb", "Thunderstorm", "Sky Judgement", "Thunderball Destruction", "Electric Flash"], awakening: false, dropChance: "Limited skin. Was obtainable from Summer Gacha (500 tokens)." },
  "Green Lightning":    { desc: "A CHROMATIC Lightning skin with a green color scheme. Limited skin from Summer Gacha or Winter Fruit Box.", moves: ["Lightning Orb", "Thunderstorm", "Sky Judgement", "Thunderball Destruction", "Electric Flash"], awakening: false, dropChance: "Limited skin. Was obtainable from Summer Gacha or Winter 2025 Fruit Box (15%)." },
  "Red Lightning":      { desc: "A CHROMATIC Lightning skin with a red color scheme. Limited skin from Party Gacha.", moves: ["Lightning Orb", "Thunderstorm", "Sky Judgement", "Thunderball Destruction", "Electric Flash"], awakening: false, dropChance: "Limited skin. Was obtainable from Party Gacha (500 tokens)." },
  // --- Portal Skins ---
  "Divine Portal":      { desc: "A CHROMATIC Portal skin with a divine golden color scheme. Limited skin from Winter 2025 Fruit Box.", moves: ["Portal Dash", "Parallel Escape", "World Warp", "Dimensional Rift", "Quantum Leap"], awakening: false, dropChance: "Limited skin. Was obtainable from Winter 2025 Fruit Box (5% chance)." },
  // --- Eagle Skins ---
  "Glacier Eagle":      { desc: "A CHROMATIC Eagle skin with an icy glacier color scheme. Limited skin from Summer Gacha or Winter Fruit Box.", moves: ["Wind Burst", "Feather Storm", "Bone Crusher", "Soaring Talon", "Flight"], awakening: false, dropChance: "Limited skin. Was obtainable from Summer Gacha or Winter 2025 Fruit Box (25%)." },
  "Requiem Eagle":      { desc: "A CHROMATIC Eagle skin with a dark requiem color scheme. Limited skin from Summer Gacha.", moves: ["Wind Burst", "Feather Storm", "Bone Crusher", "Soaring Talon", "Flight"], awakening: false, dropChance: "Limited skin. Was obtainable from Summer Gacha (500 tokens)." },
  "Matrix Eagle":       { desc: "A CHROMATIC Eagle skin with a green matrix color scheme. Limited skin from Summer Gacha.", moves: ["Wind Burst", "Feather Storm", "Bone Crusher", "Soaring Talon", "Flight"], awakening: false, dropChance: "Limited skin. Was obtainable from Summer Gacha (500 tokens)." },
  "Parrot Eagle":       { desc: "A premium CHROMATIC Eagle skin with a colorful parrot color scheme. Offsale Robux item.", moves: ["Wind Burst", "Feather Storm", "Bone Crusher", "Soaring Talon", "Flight"], awakening: false, dropChance: "Limited skin. Was sold for 499 Robux (offsale)." },
  // --- Bomb Skins ---
  "Nuclear Bomb":       { desc: "A CHROMATIC Bomb skin with a nuclear green color scheme. Limited skin from Summer Gacha.", moves: ["Targeted Bomb", "Bomb Grab", "Land Mines", "Self Destruct", "Explosive Jump"], awakening: false, dropChance: "Limited skin. Was obtainable from Summer Gacha (500 tokens)." },
  "Thermite Bomb":      { desc: "A CHROMATIC Bomb skin with a thermite orange color scheme. Limited skin from Summer Gacha.", moves: ["Targeted Bomb", "Bomb Grab", "Land Mines", "Self Destruct", "Explosive Jump"], awakening: false, dropChance: "Limited skin. Was obtainable from Summer Gacha (500 tokens)." },
  "Azura Bomb":         { desc: "A CHROMATIC Bomb skin with an azure blue color scheme. Limited skin from Summer Gacha.", moves: ["Targeted Bomb", "Bomb Grab", "Land Mines", "Self Destruct", "Explosive Jump"], awakening: false, dropChance: "Limited skin. Was obtainable from Summer Gacha (500 tokens)." },
  "Celebration Bomb":   { desc: "A CHROMATIC Bomb skin with a festive celebration color scheme. Limited skin from Party Gacha.", moves: ["Targeted Bomb", "Bomb Grab", "Land Mines", "Self Destruct", "Explosive Jump"], awakening: false, dropChance: "Limited skin. Was obtainable from Party Gacha or Winter 2025 Fruit Box (33%)." },
  // --- Pain Skins ---
  "Sadness Pain":       { desc: "A CHROMATIC Pain skin with a blue sadness color scheme. Limited skin from Summer Gacha.", moves: ["Fury Jab", "Rage Release", "Agony Nuke", "Torturing Pulse", "Torment Warp"], awakening: false, dropChance: "Limited skin. Was obtainable from Summer Gacha (500 tokens)." },
  "Torment Pain":       { desc: "A CHROMATIC Pain skin with a dark torment color scheme. Limited skin from Summer Gacha.", moves: ["Fury Jab", "Rage Release", "Agony Nuke", "Torturing Pulse", "Torment Warp"], awakening: false, dropChance: "Limited skin. Was obtainable from Summer Gacha or Winter 2025 Fruit Box (20%)." },
  "Frustration Pain":   { desc: "A CHROMATIC Pain skin with a red frustration color scheme. Limited skin from Summer Gacha.", moves: ["Fury Jab", "Rage Release", "Agony Nuke", "Torturing Pulse", "Torment Warp"], awakening: false, dropChance: "Limited skin. Was obtainable from Summer Gacha (500 tokens)." },
  "Celestial Pain":     { desc: "A CHROMATIC Pain skin with a celestial gold color scheme. Limited skin from Celestial Gacha.", moves: ["Fury Jab", "Rage Release", "Agony Nuke", "Torturing Pulse", "Torment Warp"], awakening: false, dropChance: "Limited skin. Was obtainable from Celestial Gacha (250 tokens)." },
  "Super Spirit Pain":  { desc: "A CHROMATIC Pain skin with a super spirit purple color scheme. Limited skin from Party Gacha.", moves: ["Fury Jab", "Rage Release", "Agony Nuke", "Torturing Pulse", "Torment Warp"], awakening: false, dropChance: "Limited skin. Was obtainable from Party Gacha (500 tokens)." },
  // --- Dragon Skins ---
  "Ember Dragon":       { desc: "A CHROMATIC Dragon skin with a fiery ember color scheme. Limited skin from Winter 2025 Fruit Box (1% chance).", moves: ["Blazing Claws", "Heatwave Cannon", "Infernal Pincer", "Scorching Downfall", "Imperial Evolution", "Draconic Soar"], awakening: false, dropChance: "CHROMATIC Dragon skin. Was obtainable from Winter 2025 Fruit Box (1% chance)." },
  "Eclipse Dragon":     { desc: "A CHROMATIC Dragon skin with an eclipse dark purple color scheme. Sold for 1999 Robux (offsale).", moves: ["Blazing Claws", "Heatwave Cannon", "Infernal Pincer", "Scorching Downfall", "Imperial Evolution", "Draconic Soar"], awakening: false, dropChance: "CHROMATIC Dragon skin. Was sold for 1999 Robux (offsale)." },
  "Blood Moon Dragon":  { desc: "A CHROMATIC Dragon skin with a blood moon red color scheme. Limited offsale skin.", moves: ["Blazing Claws", "Heatwave Cannon", "Infernal Pincer", "Scorching Downfall", "Imperial Evolution", "Draconic Soar"], awakening: false, dropChance: "CHROMATIC Dragon skin. Limited offsale skin." },
  "Phoenix Sky Dragon": { desc: "A CHROMATIC Dragon skin with a phoenix sky orange color scheme. Limited offsale skin.", moves: ["Blazing Claws", "Heatwave Cannon", "Infernal Pincer", "Scorching Downfall", "Imperial Evolution", "Draconic Soar"], awakening: false, dropChance: "CHROMATIC Dragon skin. Limited offsale skin." },
  "Violet Night Dragon":{ desc: "A CHROMATIC Dragon skin with a violet night color scheme. Limited offsale skin.", moves: ["Blazing Claws", "Heatwave Cannon", "Infernal Pincer", "Scorching Downfall", "Imperial Evolution", "Draconic Soar"], awakening: false, dropChance: "CHROMATIC Dragon skin. Limited offsale skin." },
  "Galaxy Empyrean":    { desc: "A limited Empyrean skin with a cosmic galaxy color scheme. The rarest Kitsune mutation variant.", moves: ["Celestial Slash", "Divine Enchantment", "Infernal Tails", "Empyrean Firestorm", "Transformation", "Heavenly Assault"], awakening: false, dropChance: "Limited Empyrean skin. Event-exclusive." },
  "Fruit Notifier":    { desc: "Notifies you when a fruit spawns and shows distance. Only works if you're in the server when it spawns.", moves: [], awakening: false, dropChance: "Purchasable gamepass (2700 Robux)" },
  "Dark Blade":        { desc: "A mythical sword that can be upgraded to V2 via The Son Quest. Slayer Skin (V3) also available.", moves: [], awakening: false, dropChance: "Purchasable gamepass (1200 Robux)" },
  "Mythical Scrolls":  { desc: "Used to enchant weapons with blessings. 10% chance to give a Blessing. 3x scrolls per purchase.", moves: [], awakening: false, dropChance: "Purchasable gamepass (1500 Robux)" },
  "Legendary Scrolls": { desc: "Used to enchant weapons with blessings. 3% chance to give a Blessing. 5x scrolls per purchase.", moves: [], awakening: false, dropChance: "Purchasable gamepass (800 Robux)" },
  "+1 Fruit Storage":  { desc: "Permanently adds +1 extra slot to store fruits in your inventory. Stacks with multiple purchases.", moves: [], awakening: false, dropChance: "Purchasable gamepass (400 Robux)" },
  "2x Mastery":        { desc: "Doubles all mastery EXP gained from defeating NPCs. Affects item mastery, not player levels.", moves: [], awakening: false, dropChance: "Purchasable gamepass (450 Robux)" },
  "2x Money":          { desc: "Doubles Money earned from NPCs and quests. Does not affect chest loot.", moves: [], awakening: false, dropChance: "Purchasable gamepass (450 Robux)" },
  "2x Boss Drops":     { desc: "Doubles the chance for bosses to drop items like swords, accessories, etc.", moves: [], awakening: false, dropChance: "Purchasable gamepass (350 Robux)" },
  "Fast Boats":        { desc: "Grants access to Miracle (free, 2nd fastest) and The Sentinel (1000$ spawn, fastest boat).", moves: [], awakening: false, dropChance: "Purchasable gamepass (350 Robux)" }
};

if (typeof module !== "undefined") {
  module.exports = { FRUITS, FRUITS_META, FRUITS_DETAIL };
}
